export const permaQuestions = [
  { id: 1, text: "Hangtod unsa nimo mabati nga naay purpose ug meaning ang imong trabaho?", labels: ["Wala", "Panagsa", "Usahay", "Kanunay", "Permi"] },
  { id: 2, text: "Kanus-a nimo mabatian nga naa kay progress sa imong work goals?", labels: ["Wala", "Panagsa", "Usahay", "Kanunay", "Permi"] },
  { id: 3, text: "Sa trabaho, unsa ka kanunay maka absorb o ma-focus sa imong ginabuhat?", labels: ["Wala", "Panagsa", "Usahay", "Kanunay", "Permi"] },
  { id: 4, text: "Sa kinatibuk-an, unsaon nimo paghulagway ang imong panglawas?", labels: ["Grabe ka ubos", "Ubos", "Sakto lang", "Taas", "Grabe ka taas"] },
  { id: 5, text: "Sa trabaho, unsa ka kanunay ka makabati og kalipay?", labels: ["Wala", "Panagsa", "Usahay", "Kanunay", "Permi"] },
  { id: 6, text: "Hangtod unsa ka dako ang tabang ug support nga imong madawat gikan sa imong mga kauban sa trabaho kung kinahanglan nimo?", labels: ["Wala", "Panagsa", "Usahay", "Kanunay", "Permi"] },
  { id: 7, text: "Sa trabaho, unsa ka kanunay ka makabati og kabalaka?", labels: ["Wala", "Panagsa", "Usahay", "Kanunay", "Permi"] },
  { id: 8, text: "Unsa ka kanunay nimo makab-ot ang importanteng mga tumong sa trabaho nga imong gi-set?", labels: ["Wala", "Panagsa", "Usahay", "Kanunay", "Permi"] },
  { id: 9, text: "Sa overall, hangtod unsa nimo mabati nga valuable ug meaningful ang imong trabaho?", labels: ["Wala", "Panagsa", "Usahay", "Kanunay", "Permi"] },
  { id: 10, text: "Sa trabaho, unsa ka kanunay ka makabati og positibong pagbati?", labels: ["Wala", "Panagsa", "Usahay", "Kanunay", "Permi"] },
  { id: 11, text: "Hangtod unsa nimo mabati nga interested ug excited ka sa imong trabaho?", labels: ["Wala", "Panagsa", "Usahay", "Kanunay", "Permi"] },
  { id: 12, text: "Sa trabaho, unsa ka kanunay ka makabati nga nag-inusara?", labels: ["Wala", "Panagsa", "Usahay", "Kanunay", "Permi"] },
  { id: 13, text: "Unsa ka satisfied sa imong health karon?", labels: ["Grabe ka ubos", "Ubos", "Sakto lang", "Taas", "Grabe ka taas"] },
  { id: 14, text: "Sa trabaho, unsa ka kanunay ka makabati og kasuko?", labels: ["Wala", "Panagsa", "Usahay", "Kanunay", "Permi"] },
  { id: 15, text: "Hangtod unsa nimo mabati nga gi-appreciate ka sa imong mga kauban sa trabaho?", labels: ["Wala", "Panagsa", "Usahay", "Kanunay", "Permi"] },
  { id: 16, text: "Unsa ka kanunay nimo mahimo og tarong ang imong mga responsibilidad sa trabaho?", labels: ["Wala", "Panagsa", "Usahay", "Kanunay", "Permi"] },
  { id: 17, text: "Hangtod unsa nimo mabati nga klaro ang direksyon sa imong trabaho?", labels: ["Wala", "Panagsa", "Usahay", "Kanunay", "Permi"] },
  { id: 18, text: "Kung e kompara nimo imong kaugalingon sa uban nga parehas nimog edad ug gender, unsaon nimo pagtan-aw ang imong panglawas?", labels: ["Grabe ka ubos", "Ubos", "Sakto lang", "Taas", "Grabe ka taas"] },
  { id: 19, text: "Unsa ka satisfied sa imong professional relationships?", labels: ["Grabe ka ubos", "Ubos", "Sakto lang", "Taas", "Grabe ka taas"] },
  { id: 20, text: "Sa trabaho, unsa ka kanunay ka makabati og kasubo?", labels: ["Wala", "Panagsa", "Usahay", "Kanunay", "Permi"] },
  { id: 21, text: "Sa trabaho, unsa ka kanunay ka malimot sa oras samtang nagbuhat ka og butang nga imong ganahan?", labels: ["Wala", "Panagsa", "Usahay", "Kanunay", "Permi"] },
  { id: 22, text: "Sa trabaho, hangtod unsa nimo mabati nga kontento ka?", labels: ["Wala", "Panagsa", "Usahay", "Kanunay", "Permi"] },
  { id: 23, text: "Sa overall, unsa ka kamalipayon sa imong trabaho?", labels: ["Grabe ka ubos", "Ubos", "Sakto lang", "Taas", "Grabe ka taas"] },
];